#Requires -Version 5.1
<#
.SYNOPSIS
    Email alert companion for ERP_HealthCheck.ps1

.DESCRIPTION
    Reads the plain-text status files (_CRITICAL.txt / _HEALTHY.txt) generated by
    ERP_HealthCheck.ps1 and sends a formatted HTML email notification via SMTP.

    A built-in -TestEmail switch verifies SMTP connectivity end-to-end before you
    rely on scheduled alerts — if the test email arrives in your inbox, the SMTP
    settings are correct and real alerts will work.

.EXAMPLE
    # ── Step 1: Verify SMTP settings (no status file required)
    .\ERP_HealthCheck_EmailAlert.ps1 -TestEmail

    # ── Step 2: Send real alerts (reads latest ERP_Health_*_CRITICAL.txt)
    .\ERP_HealthCheck_EmailAlert.ps1

    # ── Optional: pass credentials at runtime (avoids hard-coded passwords)
    .\ERP_HealthCheck_EmailAlert.ps1 -SmtpCredential (Get-Credential)

    # ── Process a specific status file directly
    .\ERP_HealthCheck_EmailAlert.ps1 -StatusFile 'C:\Reports\ERP_Health_20260309_CRITICAL.txt'

    # ── Scan a custom reports folder
    .\ERP_HealthCheck_EmailAlert.ps1 -ReportsFolder 'D:\InfraReports'

    By default only CRITICAL status files trigger an email.  Set
    $AlertOnHealthy = $true to also receive confirmation emails for healthy runs.

.PARAMETER TestEmail
    Sends a single test email to verify SMTP connectivity and recipient settings.
    No status file is required.  If the email arrives, your configuration is
    correct and scheduled alerts will work.

.PARAMETER StatusFile
    Full path to a specific status file to process.  The script sends an alert
    for that single file only, bypassing the normal folder scan.

.PARAMETER ReportsFolder
    Path to the folder containing ERP_Health_* status files.
    Defaults to the 'Reports' subfolder next to this script.

.PARAMETER SmtpCredential
    A PSCredential for SMTP authentication.  Passing credentials at runtime is
    more secure than storing a password in this script.
    Example: .\ERP_HealthCheck_EmailAlert.ps1 -SmtpCredential (Get-Credential)

.NOTES
    Version    : 1.0.0
    Author     : Tushar Gudde
    Requires   : PowerShell 5.1+, SMTP relay accessible from this server
    Permissions: Network access to SMTP relay
    Companion  : ERP_HealthCheck.ps1  (set $EnableStatusFile = $true)
#>

param(
    [switch]$TestEmail,
    [string]$StatusFile    = '',
    [string]$ReportsFolder = '',
    # Preferred: pass -SmtpCredential (Get-Credential) so the password is not
    # stored in plain text inside this file.
    [System.Management.Automation.PSCredential]$SmtpCredential = $null
)

# ════════════════════════════════════════════════════════════════════════════════
# CONFIGURATION — edit this section before first use
# ════════════════════════════════════════════════════════════════════════════════

# ── SMTP Settings ──────────────────────────────────────────────────────────────
$SmtpServer  = 'smtp.yourdomain.com'       # SMTP relay hostname or IP
$SmtpPort    = 587                         # 587 (STARTTLS) | 465 (SSL) | 25 (plain)
$SmtpUseSsl  = $true                       # Enable TLS/SSL

# ── SMTP Authentication ───────────────────────────────────────────────────────
# Preferred: pass -SmtpCredential (Get-Credential) on the command line.
# The plain-text fallback below is for automated/unattended scenarios only.
# SECURITY: Store secrets in Windows Credential Manager or a vault, not here.
$SmtpUsername = ''                         # Used only when -SmtpCredential is NOT supplied
$SmtpPassword = ''                         # Plain-text fallback — avoid if possible

# ── Email Addresses ────────────────────────────────────────────────────────────
$FromAddress = 'erphealth@yourdomain.com'  # Sender address
$ToAddresses = @('admin@yourdomain.com')   # One or more recipient addresses
$CcAddresses = @()                         # CC list (optional)

# ── Alert Behaviour ────────────────────────────────────────────────────────────
$AlertOnCritical = $true    # Send email when a CRITICAL status file is found
$AlertOnHealthy  = $false   # Also send email when status is HEALTHY (optional)

# How many status files to process per run (0 = all, 1 = latest only)
$MaxFilesToProcess = 1

# ════════════════════════════════════════════════════════════════════════════════

$ScriptVersion = '1.0.0'
$ScriptDir     = Split-Path -Parent $MyInvocation.MyCommand.Definition
if ([string]::IsNullOrEmpty($ScriptDir)) { $ScriptDir = $PWD.Path }

# ── HELPER FUNCTIONS ──────────────────────────────────────────────────────────
function Write-Log {
    param([string]$Msg, [string]$Color = 'Cyan')
    Write-Host "  [$(Get-Date -Format 'HH:mm:ss')] $Msg" -ForegroundColor $Color
}

function HtmlEscape {
    param([string]$Text)
    if ([string]::IsNullOrEmpty($Text)) { return '' }
    $Text = $Text -replace '&', '&amp;'
    $Text = $Text -replace '<', '&lt;'
    $Text = $Text -replace '>', '&gt;'
    $Text = $Text -replace '"', '&quot;'
    $Text = $Text -replace "'", '&#39;'
    return $Text
}

function Build-HtmlEmail {
    <#
    .SYNOPSIS  Builds a formatted HTML email body from plain-text status content.
    #>
    param(
        [string]$StatusContent,
        [bool]  $IsCritical,
        [bool]  $IsTest = $false
    )

    $bgBanner    = if ($IsTest)          { '#1f6feb' }
                   elseif ($IsCritical)  { '#da3633' }
                   else                  { '#2ea043' }

    $statusLabel = if ($IsTest)          { '&#x1F9EA; TEST EMAIL &mdash; SMTP Connectivity Check' }
                   elseif ($IsCritical)  { '&#x26A0; CRITICAL ALERT' }
                   else                  { '&#x2714; HEALTHY STATE' }

    $safeContent = HtmlEscape $StatusContent

    return @"
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ERP Health Check Email Alert</title>
</head>
<body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#0d1117;color:#c9d1d9;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0d1117;">
    <tr>
      <td align="center" style="padding:24px 16px;">
        <table width="660" cellpadding="0" cellspacing="0"
               style="max-width:660px;background:#161b22;border:1px solid #30363d;border-radius:8px;overflow:hidden;">

          <!-- Banner -->
          <tr>
            <td style="background:$bgBanner;padding:16px 24px;">
              <h1 style="margin:0;font-size:1.15rem;color:#fff;font-weight:700;">
                &#x1F4CA; ERP Server Health Check &nbsp;&mdash;&nbsp; $statusLabel
              </h1>
            </td>
          </tr>

          <!-- Status content (pre-formatted) -->
          <tr>
            <td style="padding:20px 24px;">
              <pre style="margin:0;padding:16px;white-space:pre-wrap;word-break:break-word;
                          font-family:Consolas,'SFMono-Regular',monospace;font-size:13px;
                          line-height:1.5;color:#c9d1d9;background:#0d1117;
                          border:1px solid #30363d;border-radius:6px;overflow-x:auto;">$safeContent</pre>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="background:#010409;padding:12px 24px;border-top:1px solid #30363d;">
              <p style="margin:0;font-size:12px;color:#8b949e;">
                ERP Health Check v$ScriptVersion &nbsp;|&nbsp;
                Email sent by ERP_HealthCheck_EmailAlert.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>
"@
}

function Resolve-SmtpCredential {
    <# Returns a PSCredential or $null if none is configured. #>
    $cred = $SmtpCredential
    if ($null -eq $cred -and -not [string]::IsNullOrWhiteSpace($SmtpUsername)) {
        $securePwd = ConvertTo-SecureString $SmtpPassword -AsPlainText -Force
        $cred      = New-Object System.Management.Automation.PSCredential($SmtpUsername, $securePwd)
    }
    return $cred
}

function Build-EmailSubject {
    <# Returns a consistently formatted email subject line. #>
    param([string]$Tag)
    return "ERP Health Check - $Tag - $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
}

function Send-Email {
    <# Low-level mailer shared by test and production paths. #>
    param(
        [string]$Subject,
        [string]$HtmlBody
    )
    $mailParams = @{
        SmtpServer  = $SmtpServer
        Port        = $SmtpPort
        From        = $FromAddress
        To          = $ToAddresses
        Subject     = $Subject
        Body        = $HtmlBody
        BodyAsHtml  = $true
        UseSsl      = $SmtpUseSsl
        ErrorAction = 'Stop'
    }
    if ($CcAddresses.Count -gt 0) { $mailParams['Cc'] = $CcAddresses }
    $cred = Resolve-SmtpCredential
    if ($null -ne $cred) { $mailParams['Credential'] = $cred }
    Send-MailMessage @mailParams
}

function Send-StatusEmail {
    <# Sends the alert email for a single status file. #>
    param(
        [string]$FilePath,
        [string]$FileContent
    )
    $isCritical = $FilePath -match '_CRITICAL\.txt$'
    $fileName   = Split-Path $FilePath -Leaf
    $subjectTag = if ($isCritical) { '*** CRITICAL ALERT ***' } else { 'Healthy State' }
    $subject    = Build-EmailSubject -Tag $subjectTag
    $htmlBody   = Build-HtmlEmail -StatusContent $FileContent -IsCritical $isCritical

    try {
        Send-Email -Subject $subject -HtmlBody $htmlBody
        $color = if ($isCritical) { 'Red' } else { 'Green' }
        Write-Log "[OK] Email sent  -  Subject: $subject" $color
    } catch {
        Write-Warning "Failed to send email for '$fileName': $_"
    }
}

# ── BANNER ────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "+==============================================================+" -ForegroundColor DarkGreen
Write-Host "|   ERP Health Check - Email Alert  v$ScriptVersion                  |" -ForegroundColor DarkGreen
Write-Host "+==============================================================+" -ForegroundColor DarkGreen
Write-Host ""

# ════════════════════════════════════════════════════════════════════════════════
# -TestEmail MODE
# Sends a test email to verify SMTP settings without needing a status file.
# ════════════════════════════════════════════════════════════════════════════════
if ($TestEmail) {
    Write-Log "TEST EMAIL MODE - verifying SMTP connectivity..." 'Cyan'
    Write-Log "  SMTP Server : $SmtpServer : $SmtpPort  (SSL: $SmtpUseSsl)"
    Write-Log "  From        : $FromAddress"
    Write-Log "  To          : $($ToAddresses -join ', ')"
    Write-Host ""

    $testContent  = "============================================================`r`n"
    $testContent += " ERP SERVER HEALTH CHECK  -  SMTP TEST EMAIL`r`n"
    $testContent += "============================================================`r`n"
    $testContent += " This is a test email sent by ERP_HealthCheck_EmailAlert.ps1`r`n"
    $testContent += "`r`n"
    $testContent += " SMTP Server : $SmtpServer`r`n"
    $testContent += " SMTP Port   : $SmtpPort`r`n"
    $testContent += " Use SSL     : $SmtpUseSsl`r`n"
    $testContent += " From        : $FromAddress`r`n"
    $testContent += " To          : $($ToAddresses -join ', ')`r`n"
    $testContent += "`r`n"
    $testContent += " If you received this email, your SMTP settings are correct.`r`n"
    $testContent += " The alert system is ready to send ERP health reports.`r`n"
    $testContent += "============================================================`r`n"
    $testContent += " Sent at : $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`r`n"
    $testContent += " Script  : ERP_HealthCheck_EmailAlert.ps1 v$ScriptVersion`r`n"
    $testContent += "============================================================`r`n"

    $subject  = Build-EmailSubject -Tag 'TEST EMAIL'
    $htmlBody = Build-HtmlEmail -StatusContent $testContent -IsCritical $false -IsTest $true

    try {
        Send-Email -Subject $subject -HtmlBody $htmlBody
        Write-Host ""
        Write-Host "  [SUCCESS] Test email sent successfully!" -ForegroundColor Green
        Write-Host "  Check your inbox at: $($ToAddresses -join ', ')" -ForegroundColor Green
        Write-Host ""
        Write-Host "  SMTP settings are correct." -ForegroundColor Green
        Write-Host "  Run this script without -TestEmail to send real health alerts." -ForegroundColor Cyan
    } catch {
        Write-Host ""
        Write-Host "  [FAILED] Could not send test email." -ForegroundColor Red
        Write-Host "  Error    : $_" -ForegroundColor Red
        Write-Host ""
        Write-Host "  Check the following settings in this script:" -ForegroundColor Yellow
        Write-Host "    `$SmtpServer   = '$SmtpServer'" -ForegroundColor Yellow
        Write-Host "    `$SmtpPort     = $SmtpPort" -ForegroundColor Yellow
        Write-Host "    `$SmtpUseSsl   = `$$SmtpUseSsl" -ForegroundColor Yellow
        Write-Host "    `$FromAddress  = '$FromAddress'" -ForegroundColor Yellow
        Write-Host "    `$SmtpUsername (if authentication is required)" -ForegroundColor Yellow
        exit 1
    }

    Write-Host ""
    Write-Host "===============================================================" -ForegroundColor DarkGreen
    Write-Host "  Test email complete." -ForegroundColor DarkGreen
    Write-Host "===============================================================" -ForegroundColor DarkGreen
    Write-Host ""
    exit 0
}

# ════════════════════════════════════════════════════════════════════════════════
# SINGLE-FILE MODE (when -StatusFile is provided)
# ════════════════════════════════════════════════════════════════════════════════
if (-not [string]::IsNullOrWhiteSpace($StatusFile)) {
    if (-not (Test-Path $StatusFile)) {
        Write-Warning "Status file not found: $StatusFile"
        exit 1
    }
    Write-Log "Processing specified file: $(Split-Path $StatusFile -Leaf)"
    try {
        $content      = [System.IO.File]::ReadAllText($StatusFile, [System.Text.Encoding]::UTF8)
        $isCritFile   = $StatusFile -match '_CRITICAL\.txt$'
        $isHealthFile = $StatusFile -match '_HEALTHY\.txt$'

        if (($isCritFile -and $AlertOnCritical) -or ($isHealthFile -and $AlertOnHealthy)) {
            Send-StatusEmail -FilePath $StatusFile -FileContent $content
        } else {
            Write-Log "File does not match alert criteria (AlertOnCritical=$AlertOnCritical, AlertOnHealthy=$AlertOnHealthy). No email sent." 'Yellow'
        }
    } catch {
        Write-Warning "Could not read '$StatusFile': $_"
        exit 1
    }
    Write-Host ""
    Write-Host "  Email alert processing complete." -ForegroundColor DarkGreen
    Write-Host ""
    exit 0
}

# ════════════════════════════════════════════════════════════════════════════════
# FOLDER SCAN MODE (default — scans Reports subfolder)
# ════════════════════════════════════════════════════════════════════════════════
if ([string]::IsNullOrWhiteSpace($ReportsFolder)) {
    $ReportsFolder = Join-Path $ScriptDir 'Reports'
}

if (-not (Test-Path $ReportsFolder)) {
    Write-Warning "Reports folder not found: $ReportsFolder"
    Write-Host "  Run ERP_HealthCheck.ps1 first (with `$EnableStatusFile = `$true) to generate status files." -ForegroundColor Yellow
    exit 1
}

Write-Log "Scanning: $ReportsFolder"

$criticalFiles = @(
    Get-ChildItem -Path $ReportsFolder -Filter 'ERP_Health_*_CRITICAL.txt' -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending
)
$healthyFiles  = @(
    Get-ChildItem -Path $ReportsFolder -Filter 'ERP_Health_*_HEALTHY.txt' -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending
)

Write-Log "Found $($criticalFiles.Count) CRITICAL file(s), $($healthyFiles.Count) HEALTHY file(s)."

# Build the work list
$filesToProcess = [System.Collections.Generic.List[System.IO.FileInfo]]::new()

if ($AlertOnCritical -and $criticalFiles.Count -gt 0) {
    $pick = if ($MaxFilesToProcess -gt 0) {
        $criticalFiles | Select-Object -First $MaxFilesToProcess
    } else { $criticalFiles }
    foreach ($f in $pick) { $filesToProcess.Add($f) }
}

if ($AlertOnHealthy -and $healthyFiles.Count -gt 0) {
    $pick = if ($MaxFilesToProcess -gt 0) {
        $healthyFiles | Select-Object -First $MaxFilesToProcess
    } else { $healthyFiles }
    foreach ($f in $pick) { $filesToProcess.Add($f) }
}

if ($filesToProcess.Count -eq 0) {
    if ($criticalFiles.Count -eq 0 -and $healthyFiles.Count -eq 0) {
        Write-Warning "No ERP Health Check status files found in: $ReportsFolder"
        Write-Host "  Ensure ERP_HealthCheck.ps1 has run with `$EnableStatusFile = `$true." -ForegroundColor Yellow
    } else {
        Write-Log "No files match the configured alert criteria. No emails sent.  (AlertOnCritical=$AlertOnCritical, AlertOnHealthy=$AlertOnHealthy)" 'Yellow'
    }
} else {
    foreach ($file in $filesToProcess) {
        Write-Log "Processing: $($file.Name)"
        try {
            $content = [System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8)
            Send-StatusEmail -FilePath $file.FullName -FileContent $content
        } catch {
            Write-Warning "Could not read '$($file.Name)': $_"
        }
    }
}

Write-Host ""
Write-Host "===============================================================" -ForegroundColor DarkGreen
Write-Host "  Email alert processing complete." -ForegroundColor DarkGreen
Write-Host "===============================================================" -ForegroundColor DarkGreen
Write-Host ""
