#Requires -Version 5.1
<#
.SYNOPSIS
    Email alert companion for WDS_HealthCheck.ps1

.DESCRIPTION
    Reads the plain-text status files (_CRITICAL.txt / _HEALTHY.txt) generated by
    WDS_HealthCheck.ps1 and sends a formatted HTML email notification via SMTP.

    A built-in -TestEmail switch verifies SMTP connectivity end-to-end before you
    rely on scheduled alerts.  If the test email arrives in your inbox, the SMTP
    settings are correct and real alerts will work.

.EXAMPLE
    # -- Step 1: Verify SMTP settings (no status file required)
    .\WDS_HealthCheck_EmailAlert.ps1 -TestEmail

    # -- Step 2: Send real alerts (reads latest WDS_Health_*_CRITICAL.txt)
    .\WDS_HealthCheck_EmailAlert.ps1

    # -- Optional: pass credentials at runtime (avoids hard-coded passwords)
    .\WDS_HealthCheck_EmailAlert.ps1 -SmtpCredential (Get-Credential)

    # -- Process a specific status file directly
    .\WDS_HealthCheck_EmailAlert.ps1 -StatusFile 'C:\Reports\WDS_Health_20260309_CRITICAL.txt'

    # -- Scan a custom reports folder
    .\WDS_HealthCheck_EmailAlert.ps1 -ReportsFolder 'D:\InfraReports'

    By default only CRITICAL status files trigger an email.  Set
    $AlertOnHealthy = $true to also receive confirmation emails for healthy runs.

.PARAMETER TestEmail
    Sends a single test email to verify SMTP connectivity and recipient settings.
    No status file is required.  If the email arrives, your configuration is
    correct and scheduled alerts will work.

.PARAMETER StatusFile
    Full path to a specific status file to process.  The script sends an alert
    for that single file only, bypassing the normal folder scan.

.PARAMETER ReportsFolder
    Path to the folder containing WDS_Health_* status files.
    Defaults to the 'Reports' subfolder next to this script.

.PARAMETER SmtpCredential
    A PSCredential for SMTP authentication.  Passing credentials at runtime is
    more secure than storing a password in this script.
    Example: .\WDS_HealthCheck_EmailAlert.ps1 -SmtpCredential (Get-Credential)

.NOTES
    Version    : 1.0.0
    Author     : Tushar Gudde
    Requires   : PowerShell 5.1+, SMTP relay accessible from this server
    Permissions: Network access to SMTP relay
    Companion  : WDS_HealthCheck.ps1  (set $EnableStatusFile = $true)
#>

param(
    [switch]$TestEmail,
    [string]$StatusFile    = '',
    [string]$ReportsFolder = '',
    # Preferred: pass -SmtpCredential (Get-Credential) so the password is not
    # stored in plain text inside this file.
    [System.Management.Automation.PSCredential]$SmtpCredential = $null
)

# ================================================================================
# CONFIGURATION - edit this section before first use
# ================================================================================

# -- SMTP Settings --------------------------------------------------------------
$SmtpServer  = 'smtp.yourdomain.com'       # SMTP relay hostname or IP
$SmtpPort    = 587                         # 587 (STARTTLS) | 465 (SSL) | 25 (plain)
$SmtpUseSsl  = $true                       # Enable TLS/SSL

# -- SMTP Authentication -------------------------------------------------------
# Preferred: pass -SmtpCredential (Get-Credential) on the command line.
# The plain-text fallback below is for automated/unattended scenarios only.
# SECURITY: Store secrets in Windows Credential Manager or a vault, not here.
$SmtpUsername = ''                         # Used only when -SmtpCredential is NOT supplied
$SmtpPassword = ''                         # Plain-text fallback - avoid if possible

# -- Email Addresses ------------------------------------------------------------
$FromAddress = 'wdshealth@yourdomain.com'  # Sender address
$ToAddresses = @('admin@yourdomain.com')   # One or more recipient addresses
$CcAddresses = @()                         # CC list (optional)

# -- Alert Behaviour ------------------------------------------------------------
$AlertOnCritical = $true    # Send email when a CRITICAL status file is found
$AlertOnHealthy  = $false   # Also send email when status is HEALTHY (optional)

# How many status files to process per run (0 = all, 1 = latest only)
$MaxFilesToProcess = 1

# ================================================================================

$ScriptVersion = '1.0.0'
$ScriptDir     = Split-Path -Parent $MyInvocation.MyCommand.Definition
if ([string]::IsNullOrEmpty($ScriptDir)) { $ScriptDir = $PWD.Path }

# -- HELPER FUNCTIONS ----------------------------------------------------------
function Write-Log {
    param([string]$Msg, [string]$Color = 'Cyan')
    Write-Host "  [$(Get-Date -Format 'HH:mm:ss')] $Msg" -ForegroundColor $Color
}

function HtmlEscape {
    param([string]$Text)
    if ([string]::IsNullOrEmpty($Text)) { return '' }
    $Text = $Text -replace '&', '&amp;'
    $Text = $Text -replace '<', '&lt;'
    $Text = $Text -replace '>', '&gt;'
    $Text = $Text -replace '"', '&quot;'
    $Text = $Text -replace "'", '&#39;'
    return $Text
}

function Build-HtmlEmail {
    <#
    .SYNOPSIS Builds the HTML email body from a plain-text status file.
    #>
    param(
        [string]$StatusContent,
        [bool]  $IsCritical = $false,
        [bool]  $IsTest     = $false
    )

    $accentColour = if ($IsCritical) { '#ef4444' } elseif ($IsTest) { '#6366f1' } else { '#22c55e' }
    $statusLabel  = if ($IsTest)         { '&#x1F9EA; TEST EMAIL &mdash; SMTP Connectivity Check' }
                    elseif ($IsCritical) { '&#x26A0; CRITICAL ALERT' }
                    else                 { '&#x2714; HEALTHY STATE' }

    $safeContent = HtmlEscape $StatusContent

    return @"
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>WDS Health Check Alert</title>
</head>
<body style="margin:0;padding:0;background:#0f0f1a;font-family:'Segoe UI',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0f0f1a;">
    <tr>
      <td align="center" style="padding:24px 8px;">
        <table width="640" cellpadding="0" cellspacing="0"
               style="background:#1a1a2e;border:1px solid #2a2a4a;border-radius:10px;overflow:hidden;max-width:640px;">

          <!-- Header -->
          <tr>
            <td style="background:linear-gradient(135deg,#1e1b4b 0%,#312e81 50%,#1e1b4b 100%);
                       border-bottom:3px solid $accentColour;padding:24px;">
              <p style="margin:0 0 6px;font-size:22px;font-weight:700;color:#fff;letter-spacing:.3px;">
                &#128268; WDS <span style="color:#a78bfa;">Health Check</span>
              </p>
              <p style="margin:0;font-size:14px;color:#a78bfa;font-weight:600;">
                $statusLabel
              </p>
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding:24px;">
              <p style="margin:0 0 16px;font-size:13px;color:#94a3b8;">
                The following status report was generated by
                <b style="color:#e2e8f0;">WDS_HealthCheck.ps1</b> on
                <b style="color:#e2e8f0;">$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')</b>.
              </p>

              <!-- Status box -->
              <table width="100%" cellpadding="0" cellspacing="0"
                     style="background:#0d0d1f;border-left:4px solid $accentColour;
                            border-radius:0 6px 6px 0;margin-bottom:16px;">
                <tr>
                  <td style="padding:12px 16px;">
                    <p style="margin:0;font-size:11px;color:#94a3b8;
                              text-transform:uppercase;letter-spacing:1px;margin-bottom:4px;">
                      Status Summary
                    </p>
                    <p style="margin:0;font-size:15px;font-weight:700;color:#e2e8f0;">
                      $statusLabel
                    </p>
                  </td>
                </tr>
              </table>

              <!-- Details -->
              <p style="margin:0 0 8px;font-size:13px;color:#94a3b8;
                        text-transform:uppercase;letter-spacing:.5px;">
                Full Report Details
              </p>
              <pre style="margin:0;padding:14px 16px;
                          font-family:Consolas,'SFMono-Regular',monospace;font-size:12px;
                          line-height:1.6;color:#c9d1d9;background:#0d1117;
                          border:1px solid #30363d;border-radius:6px;overflow-x:auto;
                          white-space:pre-wrap;word-break:break-all;">$safeContent</pre>
            </td>
          </tr>

          <!-- Action Guidance -->
          <tr>
            <td style="padding:0 24px 20px;">
              <table width="100%" cellpadding="0" cellspacing="0"
                     style="background:#0d0d1f;border:1px solid #2a2a4a;border-radius:8px;">
                <tr>
                  <td style="padding:14px 16px;">
                    <p style="margin:0 0 6px;font-size:12px;color:#a78bfa;font-weight:700;
                              text-transform:uppercase;letter-spacing:.5px;">
                      Next Steps
                    </p>
                    <p style="margin:0;font-size:12px;color:#94a3b8;line-height:1.6;">
                      1. Review the full HTML report referenced in the status output above.<br/>
                      2. Address any Critical or Warning findings listed.<br/>
                      3. Re-run WDS_HealthCheck.ps1 after remediation to verify resolution.<br/>
                      4. Check WDS role, services, DHCP integration, and PXE/TFTP health.
                    </p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="background:#010409;padding:12px 24px;border-top:1px solid #30363d;">
              <p style="margin:0;font-size:12px;color:#8b949e;">
                WDS Health Check v$ScriptVersion &nbsp;|&nbsp;
                Email sent by WDS_HealthCheck_EmailAlert.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>
"@
}

function Resolve-SmtpCredential {
    <# Returns a PSCredential or $null if none is configured. #>
    $cred = $SmtpCredential
    if ($null -eq $cred -and -not [string]::IsNullOrWhiteSpace($SmtpUsername)) {
        $securePwd = ConvertTo-SecureString $SmtpPassword -AsPlainText -Force
        $cred      = New-Object System.Management.Automation.PSCredential($SmtpUsername, $securePwd)
    }
    return $cred
}

function Build-EmailSubject {
    <# Returns a consistently formatted email subject line. #>
    param([string]$Tag)
    return "WDS Health Check - $Tag - $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
}

function Send-Email {
    <# Low-level mailer shared by test and production paths. #>
    param(
        [string]$Subject,
        [string]$HtmlBody
    )
    $mailParams = @{
        SmtpServer  = $SmtpServer
        Port        = $SmtpPort
        From        = $FromAddress
        To          = $ToAddresses
        Subject     = $Subject
        Body        = $HtmlBody
        BodyAsHtml  = $true
        UseSsl      = $SmtpUseSsl
        ErrorAction = 'Stop'
    }
    if ($CcAddresses.Count -gt 0) { $mailParams['Cc'] = $CcAddresses }
    $cred = Resolve-SmtpCredential
    if ($null -ne $cred) { $mailParams['Credential'] = $cred }
    Send-MailMessage @mailParams
}

function Send-StatusEmail {
    <# Sends the alert email for a single status file. #>
    param(
        [string]$FilePath,
        [string]$FileContent
    )
    $isCritical = $FilePath -match '_CRITICAL\.txt$'
    $fileName   = Split-Path $FilePath -Leaf
    $subjectTag = if ($isCritical) { '*** CRITICAL ALERT ***' } else { 'Healthy State' }
    $subject    = Build-EmailSubject -Tag $subjectTag
    $htmlBody   = Build-HtmlEmail -StatusContent $FileContent -IsCritical $isCritical

    try {
        Send-Email -Subject $subject -HtmlBody $htmlBody
        $color = if ($isCritical) { 'Red' } else { 'Green' }
        Write-Log "[OK] Email sent  -  Subject: $subject" $color
    } catch {
        Write-Warning "Failed to send email for '$fileName': $_"
    }
}

# -- BANNER --------------------------------------------------------------------
Write-Host ""
Write-Host "+==============================================================+" -ForegroundColor DarkCyan
Write-Host "|   WDS Health Check - Email Alert  v$ScriptVersion                   |" -ForegroundColor DarkCyan
Write-Host "+==============================================================+" -ForegroundColor DarkCyan
Write-Host ""

# ================================================================================
# -TestEmail MODE
# Sends a test email to verify SMTP settings without needing a status file.
# ================================================================================
if ($TestEmail) {
    Write-Log "TEST EMAIL MODE - verifying SMTP connectivity..." 'Cyan'
    Write-Log "  SMTP Server : $SmtpServer : $SmtpPort  (SSL: $SmtpUseSsl)"
    Write-Log "  From        : $FromAddress"
    Write-Log "  To          : $($ToAddresses -join ', ')"
    Write-Host ""

    $testContent  = "============================================================`r`n"
    $testContent += " WDS HEALTH CHECK  -  SMTP TEST EMAIL`r`n"
    $testContent += "============================================================`r`n"
    $testContent += " This is a test email sent by WDS_HealthCheck_EmailAlert.ps1`r`n"
    $testContent += "`r`n"
    $testContent += " SMTP Server : $SmtpServer`r`n"
    $testContent += " SMTP Port   : $SmtpPort`r`n"
    $testContent += " Use SSL     : $SmtpUseSsl`r`n"
    $testContent += " From        : $FromAddress`r`n"
    $testContent += " To          : $($ToAddresses -join ', ')`r`n"
    $testContent += "`r`n"
    $testContent += " If you received this email, your SMTP settings are correct.`r`n"
    $testContent += " The alert system is ready to send WDS health reports.`r`n"
    $testContent += "============================================================`r`n"
    $testContent += " Sent at : $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`r`n"
    $testContent += " Script  : WDS_HealthCheck_EmailAlert.ps1 v$ScriptVersion`r`n"
    $testContent += "============================================================`r`n"

    $subject  = Build-EmailSubject -Tag 'TEST EMAIL'
    $htmlBody = Build-HtmlEmail -StatusContent $testContent -IsCritical $false -IsTest $true

    try {
        Send-Email -Subject $subject -HtmlBody $htmlBody
        Write-Host ""
        Write-Host "  [SUCCESS] Test email sent successfully!" -ForegroundColor Green
        Write-Host "  Check your inbox at: $($ToAddresses -join ', ')" -ForegroundColor Green
        Write-Host ""
        Write-Host "  SMTP settings are correct." -ForegroundColor Green
        Write-Host "  Run this script without -TestEmail to send real health alerts." -ForegroundColor Cyan
    } catch {
        Write-Host ""
        Write-Host "  [FAILED] Could not send test email." -ForegroundColor Red
        Write-Host "  Error    : $_" -ForegroundColor Red
        Write-Host ""
        Write-Host "  Check the following settings in this script:" -ForegroundColor Yellow
        Write-Host "    `$SmtpServer   = '$SmtpServer'" -ForegroundColor Yellow
        Write-Host "    `$SmtpPort     = $SmtpPort" -ForegroundColor Yellow
        Write-Host "    `$SmtpUseSsl   = `$$SmtpUseSsl" -ForegroundColor Yellow
        Write-Host "    `$FromAddress  = '$FromAddress'" -ForegroundColor Yellow
        Write-Host "    `$SmtpUsername (if authentication is required)" -ForegroundColor Yellow
        exit 1
    }

    Write-Host ""
    Write-Host "================================================================" -ForegroundColor DarkCyan
    Write-Host "  Test email complete." -ForegroundColor DarkCyan
    Write-Host "================================================================" -ForegroundColor DarkCyan
    Write-Host ""
    exit 0
}

# ================================================================================
# SINGLE-FILE MODE (when -StatusFile is provided)
# ================================================================================
if (-not [string]::IsNullOrWhiteSpace($StatusFile)) {
    if (-not (Test-Path $StatusFile)) {
        Write-Warning "Status file not found: $StatusFile"
        exit 1
    }
    Write-Log "Processing specified file: $(Split-Path $StatusFile -Leaf)"
    try {
        $content      = [System.IO.File]::ReadAllText($StatusFile, [System.Text.Encoding]::UTF8)
        $isCritFile   = $StatusFile -match '_CRITICAL\.txt$'
        $isHealthFile = $StatusFile -match '_HEALTHY\.txt$'

        if (($isCritFile -and $AlertOnCritical) -or ($isHealthFile -and $AlertOnHealthy)) {
            Send-StatusEmail -FilePath $StatusFile -FileContent $content
        } else {
            Write-Log "File does not match alert criteria (AlertOnCritical=$AlertOnCritical, AlertOnHealthy=$AlertOnHealthy). No email sent." 'Yellow'
        }
    } catch {
        Write-Warning "Could not read '$StatusFile': $_"
        exit 1
    }
    Write-Host ""
    Write-Host "  Email alert processing complete." -ForegroundColor DarkCyan
    Write-Host ""
    exit 0
}

# ================================================================================
# FOLDER SCAN MODE (default - scans Reports subfolder)
# ================================================================================
if ([string]::IsNullOrWhiteSpace($ReportsFolder)) {
    $ReportsFolder = Join-Path $ScriptDir 'Reports'
}

if (-not (Test-Path $ReportsFolder)) {
    Write-Warning "Reports folder not found: $ReportsFolder"
    Write-Host "  Run WDS_HealthCheck.ps1 first (with `$EnableStatusFile = `$true) to generate status files." -ForegroundColor Yellow
    exit 1
}

Write-Log "Scanning: $ReportsFolder"

$criticalFiles = @(
    Get-ChildItem -Path $ReportsFolder -Filter 'WDS_Health_*_CRITICAL.txt' -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending
)
$healthyFiles  = @(
    Get-ChildItem -Path $ReportsFolder -Filter 'WDS_Health_*_HEALTHY.txt' -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending
)

Write-Log "Found $($criticalFiles.Count) CRITICAL file(s), $($healthyFiles.Count) HEALTHY file(s)."

# Build the work list
$filesToProcess = [System.Collections.Generic.List[System.IO.FileInfo]]::new()

if ($AlertOnCritical -and $criticalFiles.Count -gt 0) {
    $pick = if ($MaxFilesToProcess -gt 0) {
        $criticalFiles | Select-Object -First $MaxFilesToProcess
    } else { $criticalFiles }
    foreach ($f in $pick) { $filesToProcess.Add($f) }
}

if ($AlertOnHealthy -and $healthyFiles.Count -gt 0) {
    $pick = if ($MaxFilesToProcess -gt 0) {
        $healthyFiles | Select-Object -First $MaxFilesToProcess
    } else { $healthyFiles }
    foreach ($f in $pick) { $filesToProcess.Add($f) }
}

if ($filesToProcess.Count -eq 0) {
    if ($criticalFiles.Count -eq 0 -and $healthyFiles.Count -eq 0) {
        Write-Warning "No WDS Health Check status files found in: $ReportsFolder"
        Write-Host "  Ensure WDS_HealthCheck.ps1 has run with `$EnableStatusFile = `$true." -ForegroundColor Yellow
    } else {
        Write-Log "No files match the configured alert criteria. No emails sent.  (AlertOnCritical=$AlertOnCritical, AlertOnHealthy=$AlertOnHealthy)" 'Yellow'
    }
} else {
    foreach ($file in $filesToProcess) {
        Write-Log "Processing: $($file.Name)"
        try {
            $content = [System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8)
            Send-StatusEmail -FilePath $file.FullName -FileContent $content
        } catch {
            Write-Warning "Could not read '$($file.Name)': $_"
        }
    }
}

Write-Host ""
Write-Host "================================================================" -ForegroundColor DarkCyan
Write-Host "  WDS Email alert processing complete." -ForegroundColor DarkCyan
Write-Host "================================================================" -ForegroundColor DarkCyan
Write-Host ""
