#Requires -Version 5.1
<#
.SYNOPSIS
    Email alert companion for AD_HealthCheck.ps1

.DESCRIPTION
    Reads the plain-text status files (_CRITICAL.txt / _HEALTHY.txt) generated by
    AD_HealthCheck.ps1 and sends a formatted HTML email notification via SMTP.

.EXAMPLE
    # Run after configuring SMTP settings above (anonymous relay):
    .\AD_HealthCheck_EmailAlert.ps1

    # Run with explicit credentials (avoids plain-text password):
    .\AD_HealthCheck_EmailAlert.ps1 -SmtpCredential (Get-Credential)

    # Process a specific file:
    .\AD_HealthCheck_EmailAlert.ps1 -StatusFile 'C:\Reports\AD_Health_20260308_181050_CRITICAL.txt'

    # Custom reports folder:
    .\AD_HealthCheck_EmailAlert.ps1 -ReportsFolder 'D:\InfraReports'

    By default only CRITICAL status files trigger an email.  Set
    $AlertOnHealthy = $true to also receive confirmation emails for healthy runs.

.PARAMETER StatusFile
    Full path to a specific status file to process.  When specified, the script
    sends an alert for that single file only (bypasses folder scanning).

.PARAMETER ReportsFolder
    Path to the Reports folder to scan.  Defaults to the 'Reports' subfolder
    next to this script.

.NOTES
    Version    : 1.0.0
    Author     : Tushar Gudde
    Requires   : PowerShell 5.1+, SMTP relay accessible from this server
    Permissions: Network access to SMTP relay
#>

param(
    [string]$StatusFile    = '',
    [string]$ReportsFolder = '',
    # Optional: pass a PSCredential to avoid storing the password in this file.
    # Example: .\AD_HealthCheck_EmailAlert.ps1 -SmtpCredential (Get-Credential)
    [System.Management.Automation.PSCredential]$SmtpCredential = $null
)

# -- CONFIGURATION -------------------------------------------------------------
# SMTP Settings
$SmtpServer    = 'smtp.yourdomain.com'      # SMTP relay hostname or IP
$SmtpPort      = 587                        # 587 (STARTTLS) | 465 (SSL) | 25 (plain)
$SmtpUseSsl    = $true                      # Enable TLS/SSL

# SMTP Authentication
# Preferred method: pass -SmtpCredential (Get-Credential) on the command line so the
# password is never stored in this file.  The plain-text fallback below is provided
# only for automated/unattended scenarios where a secrets vault is not available.
# SECURITY: Store secrets in Windows Credential Manager or a vault, not in plain text.
$SmtpUsername  = ''                         # Used only when -SmtpCredential is NOT supplied
$SmtpPassword  = ''                         # Plain-text fallback - avoid if possible

# Email Addresses
$FromAddress   = 'adhealth@yourdomain.com'  # Sender address shown in From: field
$ToAddresses   = @('admin@yourdomain.com')  # One or more recipient addresses
$CcAddresses   = @()                        # CC list (optional)

# Alert Behaviour
$AlertOnCritical = $true    # Send email when a CRITICAL status file is found
$AlertOnHealthy  = $false   # Send email even when status is HEALTHY (optional)

# How many status files to process per run (0 = all, 1 = latest only, N = latest N)
$MaxFilesToProcess = 1

# ------------------------------------------------------------------------------

$ScriptVersion = '1.0.0'
$ScriptDir     = Split-Path -Parent $MyInvocation.MyCommand.Definition
if ([string]::IsNullOrEmpty($ScriptDir)) { $ScriptDir = $PWD.Path }

# -- HELPER FUNCTIONS ----------------------------------------------------------
function Write-Log {
    param([string]$Msg, [string]$Color = 'Cyan')
    Write-Host "  [$(Get-Date -Format 'HH:mm:ss')] $Msg" -ForegroundColor $Color
}

function HtmlEscape {
    param([string]$Text)
    if ([string]::IsNullOrEmpty($Text)) { return '' }
    if ($Text -match "'") { $Text = $Text -replace "'", '&#39;' }
    $Text -replace '&','&amp;' -replace '<','&lt;' -replace '>','&gt;' -replace '"','&quot;'
}

function Build-HtmlEmail {
    <#
    .SYNOPSIS  Builds a formatted HTML email body from the plain-text status content.
    #>
    param(
        [string]$StatusContent,
        [bool]  $IsCritical
    )

    $bgBanner    = if ($IsCritical) { '#da3633' } else { '#238636' }
    $statusLabel = if ($IsCritical) { '&#x26A0; CRITICAL ALERT' } else { '&#x2714; HEALTHY STATE' }
    $safeContent = HtmlEscape $StatusContent

    return @"
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AD Health Check Email Alert</title>
</head>
<body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#0d1117;color:#c9d1d9;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0d1117;">
    <tr>
      <td align="center" style="padding:24px 16px;">
        <table width="640" cellpadding="0" cellspacing="0"
               style="max-width:640px;background:#161b22;border:1px solid #30363d;border-radius:8px;overflow:hidden;">

          <!-- Banner -->
          <tr>
            <td style="background:$bgBanner;padding:16px 24px;">
              <h1 style="margin:0;font-size:1.15rem;color:#fff;font-weight:700;">
                &#x26A1; Active Directory Health Check &nbsp;&mdash;&nbsp; $statusLabel
              </h1>
            </td>
          </tr>

          <!-- Status content (pre-formatted) -->
          <tr>
            <td style="padding:20px 24px;">
              <pre style="margin:0;padding:16px;white-space:pre-wrap;word-break:break-word;
                          font-family:Consolas,'SFMono-Regular',monospace;font-size:13px;
                          line-height:1.5;color:#c9d1d9;background:#0d1117;
                          border:1px solid #30363d;border-radius:6px;overflow-x:auto;">$safeContent</pre>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="background:#010409;padding:12px 24px;border-top:1px solid #30363d;">
              <p style="margin:0;font-size:12px;color:#8b949e;">
                AD Health Check v$ScriptVersion &nbsp;|&nbsp;
                Email sent by AD_HealthCheck_EmailAlert.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>
"@
}

function Send-StatusEmail {
    <#
    .SYNOPSIS  Sends the email for a single status file.
    #>
    param(
        [string]$FilePath,
        [string]$FileContent
    )

    $isCritical  = $FilePath -match '_CRITICAL\.txt$'
    $fileName    = Split-Path $FilePath -Leaf
    $subjectTag  = if ($isCritical) { '*** CRITICAL ALERT ***' } else { 'Healthy State' }
    $subject     = "AD Health Check - $subjectTag - $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
    $htmlBody    = Build-HtmlEmail -StatusContent $FileContent -IsCritical $isCritical

    try {
        $mailParams = @{
            SmtpServer  = $SmtpServer
            Port        = $SmtpPort
            From        = $FromAddress
            To          = $ToAddresses
            Subject     = $subject
            Body        = $htmlBody
            BodyAsHtml  = $true
            UseSsl      = $SmtpUseSsl
            ErrorAction = 'Stop'
        }

        if ($CcAddresses.Count -gt 0) {
            $mailParams['Cc'] = $CcAddresses
        }

        # Resolve credentials: prefer -SmtpCredential param; fall back to plain-text config vars.
        $resolvedCred = $SmtpCredential
        if ($null -eq $resolvedCred -and -not [string]::IsNullOrWhiteSpace($SmtpUsername)) {
            $securePwd    = ConvertTo-SecureString $SmtpPassword -AsPlainText -Force
            $resolvedCred = New-Object System.Management.Automation.PSCredential($SmtpUsername, $securePwd)
        }
        if ($null -ne $resolvedCred) {
            $mailParams['Credential'] = $resolvedCred
        }

        Send-MailMessage @mailParams
        $color = if ($isCritical) { 'Red' } else { 'Green' }
        Write-Log "[OK] Email sent  -  Subject: $subject" $color
    } catch {
        Write-Warning "Failed to send email for '$fileName': $_"
    }
}

# -- RESOLVE REPORTS FOLDER ----------------------------------------------------
if ([string]::IsNullOrWhiteSpace($ReportsFolder)) {
    $ReportsFolder = Join-Path $ScriptDir 'Reports'
}

# -- BANNER --------------------------------------------------------------------
Write-Host ""
Write-Host "+==============================================================+" -ForegroundColor DarkCyan
Write-Host "|   AD Health Check - Email Alert  v$ScriptVersion                   |" -ForegroundColor DarkCyan
Write-Host "+==============================================================+" -ForegroundColor DarkCyan
Write-Host ""

# -- SINGLE-FILE MODE (when -StatusFile is provided) --------------------------
if (-not [string]::IsNullOrWhiteSpace($StatusFile)) {
    if (-not (Test-Path $StatusFile)) {
        Write-Warning "Status file not found: $StatusFile"
        exit 1
    }
    Write-Log "Processing specified file: $(Split-Path $StatusFile -Leaf)"
    try {
        $content = [System.IO.File]::ReadAllText($StatusFile, [System.Text.Encoding]::UTF8)
        $isCritFile = $StatusFile -match '_CRITICAL\.txt$'
        $isHealthFile = $StatusFile -match '_HEALTHY\.txt$'

        if (($isCritFile -and $AlertOnCritical) -or ($isHealthFile -and $AlertOnHealthy)) {
            Send-StatusEmail -FilePath $StatusFile -FileContent $content
        } else {
            Write-Log "File does not match alert criteria (AlertOnCritical=$AlertOnCritical, AlertOnHealthy=$AlertOnHealthy). No email sent." 'Yellow'
        }
    } catch {
        Write-Warning "Could not read '$StatusFile': $_"
        exit 1
    }
    Write-Host ""
    Write-Host "  Email alert processing complete." -ForegroundColor DarkCyan
    Write-Host ""
    exit 0
}

# -- FOLDER SCAN MODE (default) -----------------------------------------------
if (-not (Test-Path $ReportsFolder)) {
    Write-Warning "Reports folder not found: $ReportsFolder"
    Write-Host "  Run AD_HealthCheck.ps1 first to generate report and status files." -ForegroundColor Yellow
    exit 1
}

Write-Log "Scanning: $ReportsFolder"

$criticalFiles = @(
    Get-ChildItem -Path $ReportsFolder -Filter 'AD_Health_*_CRITICAL.txt' -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending
)
$healthyFiles  = @(
    Get-ChildItem -Path $ReportsFolder -Filter 'AD_Health_*_HEALTHY.txt'  -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending
)

Write-Log "Found $($criticalFiles.Count) CRITICAL file(s), $($healthyFiles.Count) HEALTHY file(s)."

# Build the work list
$filesToProcess = [System.Collections.Generic.List[System.IO.FileInfo]]::new()

if ($AlertOnCritical -and $criticalFiles.Count -gt 0) {
    $pick = if ($MaxFilesToProcess -gt 0) {
        $criticalFiles | Select-Object -First $MaxFilesToProcess
    } else { $criticalFiles }
    foreach ($f in $pick) { $filesToProcess.Add($f) }
}

if ($AlertOnHealthy -and $healthyFiles.Count -gt 0) {
    $pick = if ($MaxFilesToProcess -gt 0) {
        $healthyFiles | Select-Object -First $MaxFilesToProcess
    } else { $healthyFiles }
    foreach ($f in $pick) { $filesToProcess.Add($f) }
}

if ($filesToProcess.Count -eq 0) {
    if ($criticalFiles.Count -eq 0 -and $healthyFiles.Count -eq 0) {
        Write-Warning "No AD Health Check status files found in: $ReportsFolder"
    } else {
        Write-Log "No files match the configured alert criteria. No emails sent.  (AlertOnCritical=$AlertOnCritical, AlertOnHealthy=$AlertOnHealthy)" 'Yellow'
    }
} else {
    foreach ($file in $filesToProcess) {
        Write-Log "Processing: $($file.Name)"
        try {
            $content = [System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8)
            Send-StatusEmail -FilePath $file.FullName -FileContent $content
        } catch {
            Write-Warning "Could not read '$($file.Name)': $_"
        }
    }
}

Write-Host ""
Write-Host "===============================================================" -ForegroundColor DarkCyan
Write-Host "  Email alert processing complete." -ForegroundColor DarkCyan
Write-Host "===============================================================" -ForegroundColor DarkCyan
Write-Host ""
