#Requires -Version 5.1
<#
.SYNOPSIS
    Email alert companion for ADCS_HealthCheck.ps1

.DESCRIPTION
    Reads the plain-text status files (_CRITICAL.txt / _HEALTHY.txt) generated by
    ADCS_HealthCheck.ps1 and sends a formatted HTML email notification via SMTP.

    A built-in -TestEmail switch verifies SMTP connectivity end-to-end before you
    rely on scheduled alerts — if the test email arrives, the SMTP settings are
    correct and real alerts will work.

.EXAMPLE
    # Verify SMTP settings (no status file required)
    .\ADCS_HealthCheck_EmailAlert.ps1 -TestEmail

    # Send real alerts (reads latest ADC_Health_*_CRITICAL.txt)
    .\ADCS_HealthCheck_EmailAlert.ps1

    # Pass credentials securely at runtime
    .\ADCS_HealthCheck_EmailAlert.ps1 -SmtpCredential (Get-Credential)

    # Process a specific status file
    .\ADCS_HealthCheck_EmailAlert.ps1 -StatusFile 'C:\Reports\ADC_Health_20260309_CRITICAL.txt'

    # Scan a custom reports folder
    .\ADCS_HealthCheck_EmailAlert.ps1 -ReportsFolder 'D:\PKIReports'

.PARAMETER TestEmail
    Sends a single test email to verify SMTP connectivity.
    No status file is required.

.PARAMETER StatusFile
    Full path to a specific status file to process.

.PARAMETER ReportsFolder
    Path to the folder containing ADC_Health_* status files.
    Defaults to the 'Reports' subfolder next to this script.

.PARAMETER SmtpCredential
    A PSCredential for SMTP authentication.
    Preferred over plain-text credentials stored in this script.

.NOTES
    Version    : 1.0.0
    Author     : Tushar Gudde
    Requires   : PowerShell 5.1+, SMTP relay accessible from this server
    Companion  : ADCS_HealthCheck.ps1  (set $EnableStatusFile = $true)
#>

param(
    [switch]$TestEmail,
    [string]$StatusFile    = '',
    [string]$ReportsFolder = '',
    [System.Management.Automation.PSCredential]$SmtpCredential = $null
)

# ════════════════════════════════════════════════════════════════════════════════
# CONFIGURATION
# ════════════════════════════════════════════════════════════════════════════════

$SmtpServer  = 'smtp.yourdomain.com'
$SmtpPort    = 587
$SmtpUseSsl  = $true

# Preferred: pass -SmtpCredential (Get-Credential) on the command line.
$SmtpUsername = ''
$SmtpPassword = ''

$FromAddress = 'pkihealth@yourdomain.com'
$ToAddresses = @('admin@yourdomain.com')
$CcAddresses = @()

$AlertOnCritical  = $true
$AlertOnHealthy   = $false
$MaxFilesToProcess = 1

# ════════════════════════════════════════════════════════════════════════════════

$ScriptVersion = '1.0.0'
$ScriptDir     = Split-Path -Parent $MyInvocation.MyCommand.Definition
if ([string]::IsNullOrEmpty($ScriptDir)) { $ScriptDir = $PWD.Path }

# ── HELPER FUNCTIONS ──────────────────────────────────────────────────────────
function Write-Log {
    param([string]$Msg, [string]$Color = 'Cyan')
    Write-Host "  [$(Get-Date -Format 'HH:mm:ss')] $Msg" -ForegroundColor $Color
}

function HtmlEscape {
    param([string]$Text)
    if ([string]::IsNullOrEmpty($Text)) { return '' }
    $Text = $Text -replace '&', '&amp;'
    $Text = $Text -replace '<', '&lt;'
    $Text = $Text -replace '>', '&gt;'
    $Text = $Text -replace '"', '&quot;'
    $Text = $Text -replace "'", '&#39;'
    return $Text
}

function Build-HtmlEmail {
    param(
        [string]$StatusContent,
        [bool]  $IsCritical,
        [bool]  $IsTest = $false
    )

    $bgBanner    = if ($IsTest)         { '#e05c7a' }
                   elseif ($IsCritical) { '#da3633' }
                   else                 { '#2ea043' }

    $statusLabel = if ($IsTest)         { '&#x1F9EA; TEST EMAIL &mdash; SMTP Connectivity Check' }
                   elseif ($IsCritical) { '&#x26A0; CRITICAL ALERT' }
                   else                 { '&#x2714; HEALTHY STATE' }

    $bannerText  = '#fff'

    $safeContent = HtmlEscape $StatusContent

    return @"
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ADCS PKI Health Check Email Alert</title>
</head>
<body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#0d1117;color:#c9d1d9;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0d1117;">
    <tr>
      <td align="center" style="padding:24px 16px;">
        <table width="660" cellpadding="0" cellspacing="0"
               style="max-width:660px;background:#161b22;border:1px solid #30363d;border-radius:8px;overflow:hidden;">

          <tr>
            <td style="background:$bgBanner;padding:16px 24px;">
              <h1 style="margin:0;font-size:1.15rem;color:$bannerText;font-weight:700;">
                &#x1F511; ADCS / PKI Health Check &nbsp;&mdash;&nbsp; $statusLabel
              </h1>
            </td>
          </tr>

          <tr>
            <td style="padding:20px 24px;">
              <pre style="margin:0;padding:16px;white-space:pre-wrap;word-break:break-word;
                          font-family:Consolas,'SFMono-Regular',monospace;font-size:13px;
                          line-height:1.5;color:#c9d1d9;background:#0d1117;
                          border:1px solid #30363d;border-radius:6px;overflow-x:auto;">$safeContent</pre>
            </td>
          </tr>

          <tr>
            <td style="background:#010409;padding:12px 24px;border-top:1px solid #30363d;">
              <p style="margin:0;font-size:12px;color:#8b949e;">
                ADCS Health Check v$ScriptVersion &nbsp;|&nbsp;
                Email sent by ADCS_HealthCheck_EmailAlert.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>
"@
}

function Resolve-SmtpCredential {
    $cred = $SmtpCredential
    if ($null -eq $cred -and -not [string]::IsNullOrWhiteSpace($SmtpUsername)) {
        $securePwd = ConvertTo-SecureString $SmtpPassword -AsPlainText -Force
        $cred      = New-Object System.Management.Automation.PSCredential($SmtpUsername, $securePwd)
    }
    return $cred
}

function Build-EmailSubject {
    param([string]$Tag)
    return "ADCS PKI Health Check - $Tag - $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
}

function Send-Email {
    param(
        [string]$Subject,
        [string]$HtmlBody
    )
    $mailParams = @{
        SmtpServer  = $SmtpServer
        Port        = $SmtpPort
        From        = $FromAddress
        To          = $ToAddresses
        Subject     = $Subject
        Body        = $HtmlBody
        BodyAsHtml  = $true
        UseSsl      = $SmtpUseSsl
        ErrorAction = 'Stop'
    }
    if ($CcAddresses.Count -gt 0) { $mailParams['Cc'] = $CcAddresses }
    $cred = Resolve-SmtpCredential
    if ($null -ne $cred) { $mailParams['Credential'] = $cred }
    Send-MailMessage @mailParams
}

function Send-StatusEmail {
    param(
        [string]$FilePath,
        [string]$FileContent
    )
    $isCritical = $FilePath -match '_CRITICAL\.txt$'
    $subjectTag = if ($isCritical) { '*** CRITICAL ALERT ***' } else { 'Healthy State' }
    $subject    = Build-EmailSubject -Tag $subjectTag
    $htmlBody   = Build-HtmlEmail -StatusContent $FileContent -IsCritical $isCritical

    try {
        Send-Email -Subject $subject -HtmlBody $htmlBody
        $color = if ($isCritical) { 'Red' } else { 'Green' }
        Write-Log "[OK] Email sent  -  Subject: $subject" $color
    } catch {
        Write-Warning "Failed to send email for '$(Split-Path $FilePath -Leaf)': $_"
    }
}

# ── BANNER ────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "+==============================================================+" -ForegroundColor DarkRed
Write-Host "|   ADCS PKI Health Check - Email Alert  v$ScriptVersion             |" -ForegroundColor DarkRed
Write-Host "+==============================================================+" -ForegroundColor DarkRed
Write-Host ""

# ════════════════════════════════════════════════════════════════════════════════
# -TestEmail MODE
# ════════════════════════════════════════════════════════════════════════════════
if ($TestEmail) {
    Write-Log "TEST EMAIL MODE - verifying SMTP connectivity..." 'Cyan'
    Write-Log "  SMTP Server : $SmtpServer : $SmtpPort  (SSL: $SmtpUseSsl)"
    Write-Log "  From        : $FromAddress"
    Write-Log "  To          : $($ToAddresses -join ', ')"
    Write-Host ""

    $testContent  = "============================================================`r`n"
    $testContent += " ADCS PKI HEALTH CHECK  -  SMTP TEST EMAIL`r`n"
    $testContent += "============================================================`r`n"
    $testContent += " This is a test email sent by ADCS_HealthCheck_EmailAlert.ps1`r`n"
    $testContent += "`r`n"
    $testContent += " SMTP Server : $SmtpServer`r`n"
    $testContent += " SMTP Port   : $SmtpPort`r`n"
    $testContent += " Use SSL     : $SmtpUseSsl`r`n"
    $testContent += " From        : $FromAddress`r`n"
    $testContent += " To          : $($ToAddresses -join ', ')`r`n"
    $testContent += "`r`n"
    $testContent += " If you received this email, your SMTP settings are correct.`r`n"
    $testContent += " The alert system is ready to send ADCS PKI health reports.`r`n"
    $testContent += "============================================================`r`n"
    $testContent += " Sent at : $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`r`n"
    $testContent += " Script  : ADCS_HealthCheck_EmailAlert.ps1 v$ScriptVersion`r`n"
    $testContent += "============================================================`r`n"

    $subject  = Build-EmailSubject -Tag 'TEST EMAIL'
    $htmlBody = Build-HtmlEmail -StatusContent $testContent -IsCritical $false -IsTest $true

    try {
        Send-Email -Subject $subject -HtmlBody $htmlBody
        Write-Host ""
        Write-Host "  [SUCCESS] Test email sent successfully!" -ForegroundColor Green
        Write-Host "  Check your inbox at: $($ToAddresses -join ', ')" -ForegroundColor Green
        Write-Host ""
        Write-Host "  SMTP settings are correct." -ForegroundColor Green
        Write-Host "  Run without -TestEmail to send real ADCS health alerts." -ForegroundColor Cyan
    } catch {
        Write-Host ""
        Write-Host "  [FAILED] Could not send test email." -ForegroundColor Red
        Write-Host "  Error    : $_" -ForegroundColor Red
        Write-Host ""
        Write-Host "  Check the following settings in this script:" -ForegroundColor Yellow
        Write-Host "    `$SmtpServer   = '$SmtpServer'" -ForegroundColor Yellow
        Write-Host "    `$SmtpPort     = $SmtpPort" -ForegroundColor Yellow
        Write-Host "    `$SmtpUseSsl   = `$$SmtpUseSsl" -ForegroundColor Yellow
        Write-Host "    `$FromAddress  = '$FromAddress'" -ForegroundColor Yellow
        Write-Host "    `$SmtpUsername (if authentication is required)" -ForegroundColor Yellow
        exit 1
    }

    Write-Host ""
    Write-Host "===============================================================" -ForegroundColor DarkRed
    Write-Host "  Test email complete." -ForegroundColor DarkRed
    Write-Host "===============================================================" -ForegroundColor DarkRed
    Write-Host ""
    exit 0
}

# ════════════════════════════════════════════════════════════════════════════════
# SINGLE-FILE MODE
# ════════════════════════════════════════════════════════════════════════════════
if (-not [string]::IsNullOrWhiteSpace($StatusFile)) {
    if (-not (Test-Path $StatusFile)) {
        Write-Warning "Status file not found: $StatusFile"
        exit 1
    }
    Write-Log "Processing specified file: $(Split-Path $StatusFile -Leaf)"
    try {
        $content      = [System.IO.File]::ReadAllText($StatusFile, [System.Text.Encoding]::UTF8)
        $isCritFile   = $StatusFile -match '_CRITICAL\.txt$'
        $isHealthFile = $StatusFile -match '_HEALTHY\.txt$'

        if (($isCritFile -and $AlertOnCritical) -or ($isHealthFile -and $AlertOnHealthy)) {
            Send-StatusEmail -FilePath $StatusFile -FileContent $content
        } else {
            Write-Log "File does not match alert criteria (AlertOnCritical=$AlertOnCritical, AlertOnHealthy=$AlertOnHealthy). No email sent." 'Yellow'
        }
    } catch {
        Write-Warning "Could not read '$StatusFile': $_"
        exit 1
    }
    Write-Host ""
    Write-Host "  Email alert processing complete." -ForegroundColor DarkRed
    Write-Host ""
    exit 0
}

# ════════════════════════════════════════════════════════════════════════════════
# FOLDER SCAN MODE (default)
# ════════════════════════════════════════════════════════════════════════════════
if ([string]::IsNullOrWhiteSpace($ReportsFolder)) {
    $ReportsFolder = Join-Path $ScriptDir 'Reports'
}

if (-not (Test-Path $ReportsFolder)) {
    Write-Warning "Reports folder not found: $ReportsFolder"
    Write-Host "  Run ADCS_HealthCheck.ps1 first (with `$EnableStatusFile = `$true) to generate status files." -ForegroundColor Yellow
    exit 1
}

Write-Log "Scanning: $ReportsFolder"

$criticalFiles = @(
    Get-ChildItem -Path $ReportsFolder -Filter 'ADC_Health_*_CRITICAL.txt' -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending
)
$healthyFiles  = @(
    Get-ChildItem -Path $ReportsFolder -Filter 'ADC_Health_*_HEALTHY.txt'  -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending
)

Write-Log "Found $($criticalFiles.Count) CRITICAL file(s), $($healthyFiles.Count) HEALTHY file(s)."

$filesToProcess = [System.Collections.Generic.List[System.IO.FileInfo]]::new()

if ($AlertOnCritical -and $criticalFiles.Count -gt 0) {
    $pick = if ($MaxFilesToProcess -gt 0) { $criticalFiles | Select-Object -First $MaxFilesToProcess } else { $criticalFiles }
    foreach ($f in $pick) { $filesToProcess.Add($f) }
}

if ($AlertOnHealthy -and $healthyFiles.Count -gt 0) {
    $pick = if ($MaxFilesToProcess -gt 0) { $healthyFiles | Select-Object -First $MaxFilesToProcess } else { $healthyFiles }
    foreach ($f in $pick) { $filesToProcess.Add($f) }
}

if ($filesToProcess.Count -eq 0) {
    if ($criticalFiles.Count -eq 0 -and $healthyFiles.Count -eq 0) {
        Write-Warning "No ADCS Health Check status files found in: $ReportsFolder"
        Write-Host "  Ensure ADCS_HealthCheck.ps1 has run with `$EnableStatusFile = `$true." -ForegroundColor Yellow
    } else {
        Write-Log "No files match the configured alert criteria. No emails sent.  (AlertOnCritical=$AlertOnCritical, AlertOnHealthy=$AlertOnHealthy)" 'Yellow'
    }
} else {
    foreach ($file in $filesToProcess) {
        Write-Log "Processing: $($file.Name)"
        try {
            $content = [System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8)
            Send-StatusEmail -FilePath $file.FullName -FileContent $content
        } catch {
            Write-Warning "Could not read '$($file.Name)': $_"
        }
    }
}

Write-Host ""
Write-Host "===============================================================" -ForegroundColor DarkRed
Write-Host "  Email alert processing complete." -ForegroundColor DarkRed
Write-Host "===============================================================" -ForegroundColor DarkRed
Write-Host ""
